# Generated by Django 3.0.6 on 2020-05-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=30)),
                ('ownerSurname', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('model', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('deviceType', models.CharField(max_length=30)),
            ],
        ),
    ]
